### ISSUE TITLE
Left todo from prediction pipeline

### ISSUE THREAD

**Issue by constantinpape** [bioimage-io/python-bioimage-io#83]
- [x] implement keras weights
- [x] support device as parameter in predict.py
- [x] separate forward and predict method in prediction_pipeline

**Comment by constantinpape** [comment]
I started to work on this in #86
